###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [3]:
# code here
import numpy as np  

# Generate a 3x4 array of random integers between 0 and 100  
a = np.random.randint(0, 100, size=(3, 4))  

print(a)  
# b=np.sort(a)
# print(b)
maxvalue_indices=np.argmax(a,axis=1)
print(maxvalue_indices)
sorted_indices=maxvalue_indices




[[87 11 96 79]
 [56 93 59 50]
 [ 1  8 44 25]]
[2 1 2]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [34]:
# code here
a = np.random.randint(0, 100, size=(5, 4))  
print("student marks")
print(a)
extra_subject_marks=np.random.randint(1,100,size=(5,1))
marks=np.append(a,extra_subject_marks.reshape(-1,1),axis=1)
marks
# 
six_student_marks=np.random.randint(1,100,size=(1,5))
seven_student_marks=np.random.randint(1,100,size=(1,5))
# making new array 

new_students = np.array([six_student_marks[0], seven_student_marks[0]])

marks=np.append(marks,new_students,axis=0)
marks
total_marks=np.sum(marks,axis=1)
marks=np.append(marks,total_marks.reshape(-1,1),axis=1)
marks
np.sort
# Sort the array based on the last column (total marks), non-ascending order  
sorted_marks = marks[marks[:, -1].argsort()[::-1]]  

# Show the top 2 rows  
top_2_students = sorted_marks[:2]  
top_2_students


student marks
[[71 71 68 44]
 [87 55 65 47]
 [13 22 85  9]
 [88 53 15 10]
 [ 3 54 68 98]]


array([[ 87,  55,  65,  47,  91, 345],
       [ 71,  71,  68,  44,  70, 324]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [50]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
print("unique arr column wise")
column_wise=np.unique(arr, axis=0)
print(column_wise)
print("unique arr row wise")
row_wise=np.unique(arr, axis=1)
print(row_wise)


unique arr column wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
unique arr row wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [52]:
# code here
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip the array along both axes
flipped_arr = np.flip(arr)

print("Original Array:")
print(arr)

print("Flipped Array along both axes:")
print(flipped_arr)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped Array along both axes:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [58]:
# code here
x=int(input())
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
# Find row indices where any element is larger than X
rows_with_larger_than_X = np.where(np.any(arr > x, axis=1))[0]

print("Row numbers with element larger than", x, ":", rows_with_larger_than_X)


 6


Row numbers with element larger than 6 : [1 3]


### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [ ]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [60]:
# code here
import numpy as np

# Example 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Convert 2D array to 1D using flatten()
flat_arr = arr.flatten()

# Alternatively, you can use ravel()
# flat_arr = arr.ravel()

print("Flattened 1D array:")
print(flat_arr)


Flattened 1D array:
[1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [62]:
# code here
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
min_value = arr.min()
max_value = arr.max()

# Remove the minimum and maximum values
arr = np.delete(arr, np.where(arr == min_value))
arr = np.delete(arr, np.where(arr == max_value))

print("Array after removing min and max values:")
print(arr)

Array after removing min and max values:
[335 897 548 536 637 522 761 501 893 576 908 952 537 514 767 637 715 662
 133 450 765 360 666 240 499 290 863 402 746 513 929 817 766 436 779 730
 244 727 493 339 393 549 109 848 803 634 387 375 418 957 482 203 637 368
 116 852 388 398 752 226 607 877 419 768 819 893 940 220 923 267 822 534
 677 294 486 599 743 873 853 987 692 516 204 645 731 946 494 415 540 171
 608 732 588 234 133 561 658 981 255 969 207 189 556 155 663 622 627 452
 181 851 109 308 318 408 381 664 437 496 674 255 509 949 598 863 530 815
 590 859 564 841 479 115 293 269 482 114 320 308 981 488 695 560 864 989
 160 977 761 154 214 527 573 525 968 232 668 369 213 704 703 944 526 169
 446 335 915 731 201 584 761 202 956 565 766 508 314 385 930 928 265 719
 527 251 269 725 588 686 138 291 166 496 581 115 208 677 710 294]


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [ ]:
# code here
import numpy as np

# Given array
arr = np.array([50, 120, 250, 180, 300, 90, 200, 150])

# Step 1: Limit values between 100 and 200
arr = np.clip(arr, 100, 200)

# Step 2: Sort the array
arr = np.sort(arr)

# Step 3: Compute the cumulative sum
cumulative_sum = np.cumsum(arr)

# Output results
print("Modified Array:", arr)
print("Cumulative Sum:", cumulative_sum)


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [66]:
# code herehi
a=np.random.random(5)
a

array([0.11343954, 0.00520879, 0.15918222, 0.94418476, 0.34199877])